# Setup
title:               Blog de Philippe Iannetta
tagline:             "Blog de Philippe Iannetta"
description:         "Bienvenue sur mon blog ! Un endroit pour parler sport, technologies, Linux, and more !"
url:                 ''
  #baseurl:             '/Blog'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Philippe Iannetta
  url:               https://blog.phiannetta.xyz
  email:             philippe.iannetta-contact@yahoo.com

# Publishing settings
future: false

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
