# Setup
title:               Blog de Philippe Iannetta
tagline:             "Blog de Philippe Iannetta"
description:         "Bienvenue sur mon blog ! Un endroit pour parler sport, technologies, Linux, and more !"
url:                 ''
baseurl:             '/Blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Philippe Iannetta
  url:               https://github.com/Soimuen11
  email:             madlibrarian@yahoo.com

# Gems
plugins:
  - jekyll-paginate
