# Setup
title:               The Movie-Addicted Librarian
tagline:             "A Phil Wayne's Blog"
description:         "Welcome to Phil Wayne's blog! A place to discuss technology, linguistics, cinema, literature, and so much more..."
url:                 ''
baseurl:             'Blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Phil Wayne
  url:               https://github.com/Soimuen11 
  email:             madlibrarian@yahoo.com

# Gems
plugins:
  - jekyll-paginate
